import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import Vant from 'vant'
import 'vant/lib/index.css'
import '@/styles/common.less'
import 'amfe-flexible'
import componentGlobalPlugin from '@/components/index.js'
createApp(App).use(store).use(router).use(Vant).use(componentGlobalPlugin).mount('#app')
